import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Rootin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className="h-full antialiased">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/pretendard/dist/web/static/pretendard.css"
        />
      </head>
      <body className="bg-bg-ivory flex min-h-full flex-col font-sans">
        {children}
      </body>
    </html>
  );
}
